# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    branches: [ source ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: source
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
