# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    branches: [ source ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@source
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
